spring:
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
            properties:
                hibernate:
                    format_sql: true
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        url: jdbc:mariadb://localhost:3306/rp
    application:
        name: rp
server:
    port: 8080
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /api-docs-ui.html